#index:
#    path: /
#    controller: App\Controller\DefaultController::index

vehicle:
    path: /vehicle
    controller: App\Controller\VehicleController::index

vehicle_info:
    path: /vehicle/info/{id}
    controller: App\Controller\VehicleController::info     

rent:
    path: /rent/{type}/{brand}
    controller: App\Controller\VehicleController::rent     

update_info:
    path: /update/{type}/{brand}
    controller: App\Controller\VehicleController::update     